---
title: "Publications"
description: |

---

My publications are listed on my [Google Scholar](https://scholar.google.com/citations?user=NQ2HpooAAAAJ&hl=en) and [ResearchGate](https://www.researchgate.net/profile/Jennifer-Mchenry-2) pages. Feel free to reach out me for PDFs of any papers. 

## Pre-Prints

- Starko, S., B. Timmer, L. Reshitnyk, M. Csordas, **J. McHenry**, S. Schroeder, M. Hessing-Lewis, M. Costa, A. Zielinksi, R. Zielinksi, S. Cook, R. Underhill, L. Boyer, C. Fretwell, J. Yakimishyn, W.A. Heath, C. Gruman, J.K. Baum, C. Neufeld. Temperature and food chain length, but not latitude, explain region-specific kelp forest responses to an unprecedented heatwave. [doi](https://doi.org/10.1101/2023.01.07.523109).

## 2023

- **McHenry, J.**, A. Rassweiler & S.E. Lester. Seagrass ecosystem services show complex spatial patterns and associations. (in review)

- **McHenry J.**, A. Rassweiler, G. Hernan, A.K. Dubel, A.K., C. Curtin, N. Varias, J. Barzak & S.E. Lester. Biogeographic variation in blue carbon stored by seagrass beds. _Limnology & Oceanography _ 2023.

## 2021		

- **McHenry, J.**, A. Rassweiler, G. Hernan, C.K. Uejio, S. Pau, A.K. Dubel & S.E. Lester. Modeling the biodiversity enhancement value of seagrass beds. _Diversity & Distributions_ 2021.

## 2020	

- Lester, S. E., A.K. Dubel, G. Hernan, **J. McHenry** & A. Rassweiler. Applying spatial planning principles to marine ecosystem restoration. _Frontiers in Marine Science._ 2020.

## 2019 	

- **McHenry, J.**, H. Welch H., S.E. Lester & V. Saba. Projecting marine species range shifts from ocean temperatures masks climate vulnerability. _Global Change Biology._ 2019.
 
- Siegel, K. J., R.B. Cabral, **J. McHenry**, E. Ojea, B. Owashi & S.E. Lester. Sovereign states in the Caribbean have lower social-ecological vulnerability to coral bleaching than overseas territories. _Proceedings of the Royal Society B._ 2019. 

## 2018 	

- Welch H & **J. McHenry**. Planning for dynamic process: An assemblage‐level surrogate strategy for species seasonal movement pathways. _Aquatic Conservation: Marine and Freshwater Ecosystems._ 2018. 

## 2017 	

- Lester, S. E., E.O. Ruff, K. Mayall, & **J. McHenry**. Exploring stakeholder perceptions of marine management in Bermuda. _Marine Policy._ 2017 

- **McHenry, J.**, R.S. Steneck, & D.C. Brady. Abiotic proxies for predictive mapping of near‐shore benthic assemblages: Implications for marine spatial planning. _Ecological Applications._ 2017. 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


```

