---
title: "Teaching"
description: |

---

### Climate Solutions Foundations  (GS 500 A01) - University of Victoria, [Coastal Climate Solutions Leaders Program](https://coastalclimatesolutionsleaders.org/) - *Role: Course Design & Teaching Assistant*
- This broadly interdisciplinary course provides graduate students with foundational climate change knowledge and the skills to understand, critically evaluate, communicate, and apply this new knowledge in diverse contexts. The course covers the physical climate science (including climate forcings and impacts), and the state of knowledge concerning the suite of potential climate solutions available (including climate mitigation and adaption measures). The course is team-taught and employs a variety of active learning approaches, including student-led lessons and student-led discussions. Course content is guided by the sixth Intergovernmental on Climate Change Assessment Reports (i.e., IPCC AR6) and the latest peer reviewed literature.


### Geographic Information Systems lab (GIS4043L / GIS5101L) - Florida State University, Department of Geography - *Role: Instructor*
- This is a computer-based course introducing the expanding field of geographic information, as a cross listed course open to undergraduate and graduate students. The course covers topics ranging from the GIS software and spatial data structures to the cartographic principles for mapping, metadata creation, and a variety of spatial analyses. Students also gain hands-on experience with  applying concepts and tools introduces in the lectures using ArcGIS Pro. 


### Biogeography (GEO4300) - Florida State University, Department of Geography - *Role: Graduate Teaching Assistant*
- This is an undergraduate course focused on the distributions (including past, present, and increasingly, future distributions) of species and ecosystems across space and over time.  The course is a lecture and topical reading-based course providing students with a foundation in biogeography, and also in various biogeographical concepts as they apply to contemporary issues such as land management, invasive species, and species conservation. 

### Marine Invertebrates (SMS480) - University of Maine, School of Marine Sciences, Semester by the Sea program - *Role: Graduate Teaching Assistant*
- This is an upper level undergraduate course within the Semester by the Sea program dealing with the general biology of coastal and deep-water marine benthic and pelagic invertebrates.The course involves weekly lectures on the functional morphology, behavior, ecology, phylogenetic relationships, life histories and role in human history of different marine invertebrate groups. Each lecture is paired with a field trip to local habitats surrounding the Darling Marine Center in Walpole, ME where students are able to collect and identify specimens using taxonomic keys. 

### Marine Ecology (SMS352)- University of Maine, School of Marine Sciences, Semester by the Sea program - *Role: Graduate Teaching Assistant*
- This is an upper level undergraduate course in the Semester by the Sea program providing an overview of the biotic interactions and physical forces structuring marine communities, the function and ecosystem services provided by marine communities, and the major threats to their continued function and value. Each week students hear a lecture and complete a field trip and/or experiment where they are able to make their own observations, develop and test their hypotheses, and link their findings to fundamental theories in ecology. Throughout the semester, students work on group projects based on the weekly field trips and/or laboratory experiments, focusing on the rocky intertidal habitats of the Gulf of Maine. 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

